Feature/redesign letters
ONLYOFFICE/DocSpace-server pull request #4
Opened 2023-10-04 15:03 UTC by diana-vahomskaya

[Template](https://www.figma.com/file/rsvYQREnYZAxEI9fOjAZdB/Mailing-%2F-DocSpace?type=design&node-id=130-128&mode=design&t=5cSuYakxWAPE4YbS-0)
Changed templates for letters:
HtmlMaster, SocialNetworksFooter, TextForFooterUnsubsribeDocSpace
Added new templates for Top Logo or Gif in general letters: TopGif, TopLogo

Added new substitutios: OrangeBtton, TrulyYours, SupportContact, SalesEmail.

Changed letters in general resource. For ar-Sa language templates added in comments.

2023-10-06 00:05 UTC, andreysavihin requested changes
need to move the public\images\notifications directory to the [client repository](https://github.com/ONLYOFFICE/DocSpace-client)

2023-10-06 13:12 UTC, diana-vahomskaya commented
> need to move the public\images\notifications directory to the [client repository](https://github.com/ONLYOFFICE/DocSpace-client)

deleted icons: https://github.com/ONLYOFFICE/DocSpace-server/pull/4/commits/3911f0b5c69924a105a435622ffcb890ae10c31a

icons moved to client: https://github.com/ONLYOFFICE/DocSpace-client/commit/4d11fd714088a020070d4a7710529044c3517250

2023-10-06 14:50 UTC, andreysavihin commented
**need to wait for translations into other languages before merging!**

2023-10-10 11:22 UTC, pavelbannov approved these changes

2023-10-10 11:23 UTC, merged